name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set the working directory for the following steps if your project is in a subdirectory
      - name: Install dependencies
        run: npm install
        working-directory: ./my-app  # Replace with the correct subdirectory path

      - name: Run tests
        run: npm test
        working-directory: ./my-app  # Replace with the correct subdirectory path

      - name: Build the application
        run: npm run build
        working-directory: ./my-app  # Replace with the correct subdirectory path
