name: CI/CD Pipeline

# Run this workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in this workflow
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps to execute within the job
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the Node.js version as needed

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the tests
      - name: Run tests
        run: npm test

      # Build the application
      - name: Build the application
        run: npm run build

      # Deploy to AWS S3 (as an example deployment step)
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2' # Replace with your region

  # Add more jobs for other stages if needed (e.g., deploy to other environments)
